---
title: "DDS-Practica3"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Driven Security - Actividad Evaluable 3

## Víctor López García & Lucas Carrillo Mas

### 1. Optimización de un modelo de ML

Queremos mejorar la precisión con la que un modelo de aprendizaje automático es capaz de clasificar el tráfico de red. Para ello, disponemos de un modelo ya programado que nos ofrece una cierta garantía de precisión para determinar correctamente si un determinado flujo de datos se trata en realidad de un tráfico con características similares a las de un ciberataque y, por lo tanto, el sistema de gestión y protección de la red debería bloquearlo o, por el contrario, se corresponde a patrón de tráfico de red normal. Nuestro programa es capaz ya de generar el modelo y verificar la precisión de los resultados utilizando el conjunto de datos de red.

#### Exploración de Datos

##### 1. Exploración de los datos de tráfico de red disponibles




#### Generación del modelo de ML

##### 2. Comprender el código utilizado para segmentar el conjunto de datos entre datos de entrenamiento y datos de validación.





#### Mejora de resultados del modelo

##### 3. Mejora de los resultados. Una vez ejecutado el código, comprobad la accuracy del modelo generado cuando se verifica con los datos de validación. Investigad el código y implementad al menos 2 mejoras que consigan aumentar la precisión del modelo.






